name: microlink
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Architecture & State Management
  flutter_bloc: ^8.1.3 # Cubit/Bloc state management
  get_it: ^7.6.4 # Service locator for DI

  # Code Generation & Data Classes
  freezed_annotation: ^2.4.1 # Immutable classes annotations
  json_annotation: ^4.8.1 # JSON serialization annotations

  # Navigation
  go_router: ^14.6.0 # Declarative routing

  # UI & Media
  image_picker: ^1.0.4 # Camera/gallery access
  cached_network_image: ^3.3.0 # Image caching and display
  flutter_spinkit: ^5.2.0 # Loading animations
  share_plus: ^10.1.2 # Share content to other apps

  flutter_svg: ^2.0.10

  # Network
  dio: ^5.4.0 # HTTP client for API calls
  pretty_dio_logger: ^1.3.1 # Beautiful logging for Dio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  freezed: ^2.4.7 # Code generation for data classes
  json_serializable: ^6.7.1 # JSON serialization code generation
  build_runner: ^2.4.7 # Code generation runner

  # Testing
  bloc_test: ^9.1.4 # Cubit/Bloc testing utilities

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  # - assets/illustrations/
